---
name: Sample Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print environment
        run: |
          echo "Running on $RUNNER_OS"
